#Correlation and Covariance

Two important statistical calculations are correlation and covariance, expressed in pandas by the corr( ) and cov( ) functions. These kind of calculations normally involve two Series.

In [ ]:
import pandas as pd
import numpy as np
seq2 = pd.Series([3,4,3,4,5,4,3,2],['2006','2007','2008','2009','2010','2011','2012','2013'])
seq = pd.Series([1,2,3,4,4,3,2,1],['2006','2007','2008','2009','2010','2011','2012','2013'])

In [ ]:
seq2

2006    3
2007    4
2008    3
2009    4
2010    5
2011    4
2012    3
2013    2
dtype: int64

In [ ]:
seq

2006    1
2007    2
2008    3
2009    4
2010    4
2011    3
2012    2
2013    1
dtype: int64

In [ ]:
seq.corr(seq2)

np.float64(0.7745966692414835)

In [ ]:
seq2.corr(seq)

np.float64(0.7745966692414834)

In [ ]:
seq.cov(seq2)

np.float64(0.8571428571428571)

Another case could be that covariance and correlation are applied to a single DataFrame. In this case, they return their corresponding matrices in form of two new DataFrame objects.

In [ ]:
frame2 = pd.DataFrame([[1,4,3,6],[4,5,6,1],[3,3,1,5],[4,1,6,4]],
... index=['red','blue','yellow','white'], #Entries
... columns=['ball','pen','pencil','paper']) #fields
frame2

        ball  pen  pencil  paper
red        1    4       3      6
blue       4    5       6      1
yellow     3    3       1      5
white      4    1       6      4

In [ ]:
frame2.corr()

            ball       pen    pencil     paper
ball    1.000000 -0.276026  0.577350 -0.763763
pen    -0.276026  1.000000 -0.079682 -0.361403
pencil  0.577350 -0.079682  1.000000 -0.692935
paper  -0.763763 -0.361403 -0.692935  1.000000

In [ ]:
frame2.cov()

            ball       pen    pencil     paper
ball    2.000000 -0.666667  2.000000 -2.333333
pen    -0.666667  2.916667 -0.333333 -1.333333
pencil  2.000000 -0.333333  6.000000 -3.666667
paper  -2.333333 -1.333333 -3.666667  4.666667

Using the method corrwith( ), you can calculate the pairwise correlations between the columns or rows of a data frame with a Series or another DataFrame( ).

In [ ]:
ser

red       5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [ ]:
frame2.corrwith(ser)

ball     -0.140028
pen      -0.869657
pencil    0.080845
paper     0.595854
dtype: float64

In [ ]:
frame2.corrwith(frame)

ball      0.730297
pen      -0.831522
pencil    0.210819
paper    -0.119523
dtype: float64

#“Not a Number” Data

During the previous sections we have seen how easily the missing data can be formed. They are recognizable within the data structures with the value NaN (Not a Number). So, having values that are not defined in a data structure is a condition quite common for those who carry out data analysis.

However, pandas is designed to better manage this eventuality. In fact, in this section you will learn how to treat these values so that many issues can be obviated. In fact, for example, within the pandas library, the calculation of descriptive statistics excludes NaN values implicitly.

#Assigning a NaN Value

Just in case you would like to specifically assign a NaN value to an element in a data structure, you can use the value np.NaN(or np.nan) of the NumPy library.

In [ ]:
ser = pd.Series([0,1,2,np.nan,9], index=['red','blue','yellow','white','green'])
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [ ]:
ser_new = pd.Series([0,1,2,None,9], index=['red','blue','yellow','white','green'])
ser_new

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [ ]:
ser['white'] = None
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

#Filtering Out NaN Values

There are various options to eliminate the NaN values during the data analysis. However, the elimination by hand, element by element, can be very tedious and risky, because you never get the certainty of having eliminated all the NaN values. The dropna( ) function comes to your aid.

In [ ]:
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [ ]:
ser.dropna()

red       0.0
blue      1.0
yellow    2.0
green     9.0
dtype: float64

Another possibility is to directly perform the filtering function by placing the notnull( ) in the selection condition.

In [ ]:
ser.notnull()

red        True
blue       True
yellow     True
white     False
green      True
dtype: bool

In [ ]:
ser[ser.notnull()]

red       0.0
blue      1.0
yellow    2.0
green     9.0
dtype: float64

If you’re dealing with the DataFrame it gets a little more complex. If you use the dropna( ) function on this type of object, it is sufficient that there is only one value NaN on a column or a row to eliminate it completely.

In [ ]:
frame3 = pd.DataFrame([[6,np.nan,6],[np.nan,np.nan,np.nan],[2,np.nan,5]],
... index = ['blue','green','red'],
... columns = ['ball','mug','pen'])
frame3

       ball  mug  pen
blue    6.0  NaN  6.0
green   NaN  NaN  NaN
red     2.0  NaN  5.0

Therefore to avoid having entire rows and columns disappear completely, you should specify the how
option, assigning a value of ‘all’ to it, in order to inform the dropna( ) function to delete only the rows or columns in which all elements are NaN.

In [ ]:
frame3.dropna()

Empty DataFrame
Columns: [ball, mug, pen]
Index: []

In [ ]:
frame3.dropna(how='all')

      ball  mug  pen
blue   6.0  NaN  6.0
red    2.0  NaN  5.0

In [ ]:
frame3.dropna(how='all',axis=1)

       ball  pen
blue    6.0  6.0
green   NaN  NaN
red     2.0  5.0

#Filling in NaN Occurrences

Rather than filter NaN values within data structures, with the risk of discarding them along with values that could be relevant in the context of data analysis, you could replace them with other numbers. For most purposes, the fillna( ) function could be a great choice. This method takes one argument, the value with which to replace any NaN. It can be the same for all, as in the following case.

In [ ]:
frame3.fillna(0)

       ball  mug  pen
blue    6.0  0.0  6.0
green   0.0  0.0  0.0
red     2.0  0.0  5.0

Or you can replace NaN with different values depending on the column, specifying one by one the
indexes and the associated value.

In [ ]:
frame3.fillna({'ball':1,'mug':0,'pen':99})

       ball  mug   pen
blue    6.0  0.0   6.0
green   1.0  0.0  99.0
red     2.0  0.0   5.0

#Hierarchical Indexing and Leveling

The hierarchical indexing is a very important feature of pandas, as it allows you to have multiple levels of indexes on a single axis. Somehow it gives you a way to work with data in multiple dimensions continuing to work in a two-dimensional structure.

You can start with a simple example, creating a series containing two arrays of indexes, that is, creating a structure with two levels.

In [ ]:
mser = pd.Series(np.random.rand(8),
... index=[['white','white','white','blue','blue','red','red','red'],
... ['up','down','right','up','down','up','down','left']])
mser

white  up       0.801297
       down     0.443880
       right    0.927483
blue   up       0.673047
       down     0.548736
red    up       0.599950
       down     0.972749
       left     0.882492
dtype: float64

In [ ]:
mser.index

MultiIndex([('white',    'up'),
            ('white',  'down'),
            ('white', 'right'),
            ( 'blue',    'up'),
            ( 'blue',  'down'),
            (  'red',    'up'),
            (  'red',  'down'),
            (  'red',  'left')],
           )

Through the specification of a hierarchical indexing, the selection of subsets of values is in a certain way simplified.

In fact, you can select the values for a given value of the first index, and you do it in the classic way:

In [ ]:
mser['white']

up       0.801297
down     0.443880
right    0.927483
dtype: float64

In [ ]:
#or you can select values for a given value of the second index, in the following manner:
mser[:,'up']

white    0.801297
blue     0.673047
red      0.599950
dtype: float64

In [ ]:
#Intuitively, if we want to select a specific value, you will specify both indexes.
mser['white','up']

np.float64(0.8012971857314978)

The hierarchical indexing plays a critical role in reshaping the data and group-based operations such
as creating a pivot-table. For example, the data could be used just rearranged in a data frame using a special function called unstack( ). This function converts the Series with hierarchical index in a simple DataFrame where the second set of indexes is converted into a new set of columns.

In [ ]:
mser.unstack()

           down      left     right        up
blue   0.548736       NaN       NaN  0.673047
red    0.972749  0.882492       NaN  0.599950
white  0.443880       NaN  0.927483  0.801297

If what we want is to perform the reverse operation, which is to convert a DataFrame in a Series, you will use the stack( ) function.

In [ ]:
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
frame.stack()

red     ball       0
        pen        1
        pencil     2
        paper      3
blue    ball       4
        pen        5
        pencil     6
        paper      7
yellow  ball       8
        pen        9
        pencil    10
        paper     11
white   ball      12
        pen       13
        pencil    14
        paper     15
dtype: int64

As regards the DataFrame, it is possible to define a hierarchical index both for the rows and for the
columns. At the time of the declaration of the DataFrame, you have to define an array of arrays for both the index option and the columns option.

In [ ]:
import pandas as pd
import numpy as np
mframe = pd.DataFrame(np.random.randn(16).reshape(4,4), index=[['white','white','red','red'], ['up','down','up','down']], columns=[['pen','pen','paper','paper'],[1,2,1,2]])
mframe

                 pen               paper
                   1         2         1         2
white up   -0.471842  0.680354 -0.601142 -0.512995
      down  0.073162 -0.843078  0.717531  0.538738
red   up    0.924224 -1.358672 -0.982344  1.545954
      down -0.222473 -1.172765  0.665520  1.189681

#Reordering and Sorting Levels

Occasionally, you could need to rearrange the order of the levels on an axis or do a sorting for values at a specific level.

The swaplevel( ) function accepts as argument the names assigned to the two levels that you want to interchange, and returns a new object with the two levels interchanged between them, while leaving the data
unmodified.

In [ ]:
mframe.columns.names = ['objects','id']
mframe.index.names = ['colors','status']
mframe

objects             pen               paper
id                    1         2         1         2
colors status
white  up     -0.471842  0.680354 -0.601142 -0.512995
       down    0.073162 -0.843078  0.717531  0.538738
red    up      0.924224 -1.358672 -0.982344  1.545954
       down   -0.222473 -1.172765  0.665520  1.189681

In [ ]:
mframe.swaplevel('colors','status')

objects             pen               paper
id                    1         2         1         2
status colors
up     white  -0.471842  0.680354 -0.601142 -0.512995
down   white   0.073162 -0.843078  0.717531  0.538738
up     red     0.924224 -1.358672 -0.982344  1.545954
down   red    -0.222473 -1.172765  0.665520  1.189681

In [ ]:
mframe.sort_index(level='colors')

objects             pen               paper
id                    1         2         1         2
colors status
red    down   -0.222473 -1.172765  0.665520  1.189681
       up      0.924224 -1.358672 -0.982344  1.545954
white  down    0.073162 -0.843078  0.717531  0.538738
       up     -0.471842  0.680354 -0.601142 -0.512995

In [ ]:
mframe.sort_index(level=1)

objects             pen               paper
id                    1         2         1         2
colors status
red    down   -0.222473 -1.172765  0.665520  1.189681
white  down    0.073162 -0.843078  0.717531  0.538738
red    up      0.924224 -1.358672 -0.982344  1.545954
white  up     -0.471842  0.680354 -0.601142 -0.512995

#Summary Statistic by Level

Many descriptive statistics and summary statistics performed on a DataFrame or on a Series have a level option, with which you can determine at what level the descriptive and summary statistics should be determined.
For example if you make a statistic at row level, you have to simply specify the level option with the level name.

In [ ]:
mframe

objects             pen               paper
id                    1         2         1         2
colors status
white  up     -0.471842  0.680354 -0.601142 -0.512995
       down    0.073162 -0.843078  0.717531  0.538738
red    up      0.924224 -1.358672 -0.982344  1.545954
       down   -0.222473 -1.172765  0.665520  1.189681

In [ ]:
mframe.groupby(level='colors').sum()

objects       pen               paper
id              1         2         1         2
colors
red      0.701751 -2.531437 -0.316823  2.735635
white   -0.398680 -0.162724  0.116389  0.025743

If you want to make a statistic for a given level of the column, for example, the id, you must specify the second axis as argument through the axis option set to 1.

In [ ]:
mframe.T.groupby(level='id').sum().T

id                    1         2
colors status
white  up     -1.072983  0.167359
       down    0.790693 -0.304341
red    up     -0.058120  0.187283
       down    0.443047  0.016916

# Task
## Final Task

### Subtask:
Summarize the key functionalities of pandas DataFrames covered in this comprehensive exercise.

### Reasoning:
The subtask requires summarizing the key functionalities of pandas DataFrames that have been demonstrated so far in the notebook. This will involve reviewing the DataFrame creation, element selection, value assignment, membership and filtering, deleting columns/rows, arithmetic operations, function application, statistical functions, sorting and ranking, correlation and covariance, NaN value handling, and hierarchical indexing aspects. This will conclude the comprehensive exercise on pandas DataFrames.

### Summary:

### Pandas DataFrame Key Findings

*   **DataFrame Creation**: DataFrames can be created from various data sources.
    *   **From Dictionaries**: A dictionary where keys are column names and values are lists (or Series) of data forms a DataFrame. Pandas automatically assigns a default `RangeIndex` (0, 1, 2, ...) if no index is specified.
    *   **Specifying Columns**: When creating from a dictionary, specific columns can be selected and ordered using the `columns` parameter.
    *   **Custom Index**: A custom `index` can be provided as a list of labels during DataFrame creation, similar to Series.
    *   **From NumPy Arrays**: A DataFrame can be constructed from a NumPy array, providing `index` (for rows) and `columns` (for columns) as separate parameters. This is useful for creating DataFrames with structured numerical data.
    *   **From Nested Dictionaries**: Nested dictionaries can be directly converted into DataFrames, where the outer keys become column names and inner keys become row indices, demonstrating a powerful way to handle semi-structured data. Missing values are filled with `NaN`.

*   **Element Selection**: Accessing data within DataFrames is highly flexible.
    *   **Column Selection**: Individual columns can be selected using dictionary-like notation (`frame['column_name']`) or attribute access (`frame.column_name`), returning a `Series`.
    *   **Row Selection (Integer-Location)**: Rows can be selected by their integer position using `.iloc[]`, returning a `Series` (if a single row) or a `DataFrame` (if multiple rows/slice).
    *   **Specific Cell Selection**: A single value can be accessed by first selecting the column and then the row index (`frame['column_name'][row_index]`).

*   **Value Assignment**: DataFrames allow modification and expansion.
    *   **Index and Column Naming**: `frame.index.name` and `frame.columns.name` can be used to assign descriptive names to the row and column indices.
    *   **Adding New Columns**: New columns can be added by assigning a scalar value (which broadcasts to all rows) or a `Series` (which aligns by index) to a new column name.
    *   **Updating Existing Columns/Cells**: Existing columns can be updated by assigning a new `Series` or list. Individual cell values can be updated using combined indexing (e.g., `frame['price'][2] = 3.3`).

*   **Membership and Filtering**:
    *   **`isin()` Method**: The `isin()` method checks for the presence of values within the DataFrame, returning a boolean DataFrame. This boolean DataFrame can then be used to filter the original DataFrame, showing only matching values and `NaN` for non-matching ones.
    *   **Conditional Filtering**: Rows can be filtered based on conditions applied to column values (e.g., `frame[frame['price'] < 1]`), returning a subset of the DataFrame.

*   **Deleting Columns and Rows**:
    *   **Deleting Columns**: The `del` keyword can permanently remove a column from a DataFrame (`del frame['new']`).
    *   **Dropping Rows/Columns with `drop()`**: The `drop()` method removes rows or columns specified by their labels. For columns, `axis=1` must be specified. It returns a new DataFrame without the dropped items.

*   **Transposition**:
    *   The `.T` attribute provides a simple way to transpose a DataFrame, swapping rows and columns.

*   **Index Objects**:
    *   **Immutability**: Index objects are immutable, ensuring their integrity and safe sharing across data structures.
    *   **`is_unique` Attribute**: Checks if all labels in an index are unique.
    *   **`idxmin()` and `idxmax()`**: Return the labels of the minimum and maximum values in a Series.

*   **Reindexing**:
    *   **`reindex()` Function**: Creates a new Series or DataFrame with a new index, reordering existing data and introducing `NaN` for new labels.
    *   **Filling Missing Values during Reindexing**: The `method` parameter in `reindex()` (e.g., `'ffill'` for forward fill, `'bfill'` for backward fill) can be used to fill `NaN` values created by new indices with existing data.

*   **Arithmetic Operations and Data Alignment**:
    *   **Between Series**: When performing arithmetic operations (e.g., `s1 + s2`) between two Series, pandas automatically aligns data based on common labels. Labels present in only one Series result in `NaN` in the output.
    *   **Between DataFrames**: Similarly, operations between DataFrames (`frame1 + frame2`) align both row and column labels. Non-matching labels in either axis result in `NaN`.

*   **Flexible Arithmetic Methods**:
    *   Methods like `.add()`, `.sub()`, `.div()`, and `.mul()` offer the same functionality as their operator counterparts (e.g., `frame1.add(frame2)` is equivalent to `frame1 + frame2`).
    *   **`fill_value` Parameter**: These methods include a `fill_value` parameter to specify a value to use for `NaN` entries during alignment, preventing `NaN` propagation for non-matching labels.

*   **Operations between DataFrame and Series**:
    *   Arithmetic operations between a DataFrame and a Series (e.g., `frame - ser`) align the Series' index with the DataFrame's columns by default, applying the Series operation across each row of the DataFrame. If the Series has labels not present in the DataFrame's columns, new columns are created with `NaN` values.

*   **Function Application**:
    *   **NumPy Universal Functions (`ufuncs`)**: NumPy functions like `np.sqrt()` can be directly applied to DataFrames, performing element-wise operations.
    *   **`apply()` Method**: Custom functions (lambda or user-defined) can be applied to DataFrames.
        *   Applied by default column-wise, returning a `Series`.
        *   Can be applied row-wise by setting `axis=1`.
        *   Functions can return a `Series` to generate new DataFrames (e.g., min/max for each column).

*   **Statistical Functions**:
    *   DataFrames have built-in methods for common descriptive statistics, such as `mean()`, `sum()`, and `describe()`. By default, these operate column-wise, but can be adjusted to operate row-wise using the `axis` parameter (e.g., `frame.mean(axis=1)`).

*   **Sorting and Ranking**:
    *   **`sort_index()`**: Sorts the DataFrame or Series by its index labels. Can be applied to rows or columns (`axis=1`) and in ascending or descending order (`ascending=False`).
    *   **`sort_values()`**: Sorts a DataFrame by the values of one or more specified columns (`by` parameter). For Series, it sorts by the values directly.
    *   **`rank()`**: Assigns a rank to each element in a Series, based on its value. Can be configured with `method` (e.g., `'first'`) and `ascending` parameters.

*   **Correlation and Covariance**:
    *   **`corr()` and `cov()`**: For two Series, these functions calculate their correlation and covariance. For a DataFrame, they return a correlation or covariance matrix between all pairs of columns.
    *   **`corrwith()`**: Calculates pairwise correlations of columns or rows of a DataFrame with a Series or another DataFrame.

*   **NaN Value Handling**:
    *   **Explicit Assignment**: `np.nan` or `None` can be explicitly assigned to introduce missing values.
    *   **Identification**: `isnull()` and `notnull()` methods identify missing or non-missing values, respectively, returning boolean Series or DataFrames.
    *   **Removal (`dropna()`)**:
        *   `dropna()` removes rows/columns containing `NaN` values.
        *   The `how='all'` parameter specifies removal only if *all* elements in a row/column are `NaN`.
    *   **Filling (`fillna()`)**:
        *   `fillna()` replaces `NaN` values with a specified scalar value.
        *   Can also replace `NaN`s with different values per column by passing a dictionary mapping column names to fill values.

*   **Hierarchical Indexing and Leveling**:
    *   **MultiIndex Creation**: DataFrames and Series can have multiple levels of indices on one or both axes, creating a `MultiIndex`.
    *   **Selection with MultiIndex**: Data can be selected at different levels of a MultiIndex (e.g., `mser['white']` or `mser[:,'up']`).
    *   **`unstack()` and `stack()`**:
        *   `unstack()` pivots the innermost (or specified) index level to become a new column level, converting a Series with a MultiIndex into a DataFrame.
        *   `stack()` performs the reverse operation, converting columns into an inner index level, turning a DataFrame into a Series with a MultiIndex.
    *   **Reordering Levels (`swaplevel()`)**: The order of index levels can be interchanged without altering the data.
    *   **Sorting Levels (`sort_index(level=...)`)**: Data can be sorted based on a specific level of a MultiIndex.
    *   **Summary Statistics by Level (`groupby(level=...).sum()`)**: Statistical operations can be applied to specific levels of a MultiIndex, aggregating data across those levels.

## DataFrame Creation

### Subtask:
Create DataFrames from different data sources: dictionaries, lists of lists, and NumPy arrays with custom indices and columns. Also demonstrate creating a DataFrame from a nested dictionary.

**Reasoning**:
The subtask requires creating DataFrames from various data sources as specified in the instructions. This code block will cover creating DataFrames from dictionaries (with and without specified columns/index), from NumPy arrays with custom index/columns, and from a nested dictionary, fulfilling all instructions.

In [ ]:
import pandas as pd
import numpy as np

# Data dictionary for initial DataFrame creations
data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Population': [8419000, 3980000, 2716000, 2320000, 1660000],
    'State': ['NY', 'CA', 'IL', 'TX', 'AZ']
}

# 1. Create a DataFrame df_dict from a dictionary where keys are column names and values are lists of data. Display the DataFrame.
df_dict = pd.DataFrame(data)
print("1. DataFrame created from a dictionary:")
display(df_dict)

# 2. Create a DataFrame df_dict_cols from a dictionary, explicitly specifying a subset of columns and their order using the columns parameter. Display the DataFrame.
df_dict_cols = pd.DataFrame(data, columns=['City', 'State'])
print("\n2. DataFrame from dictionary with specified columns:")
display(df_dict_cols)

# 3. Create a DataFrame df_dict_index from a dictionary, providing a custom index using the index parameter. Display the DataFrame.
custom_index = ['A', 'B', 'C', 'D', 'E']
df_dict_index = pd.DataFrame(data, index=custom_index)
print("\n3. DataFrame from dictionary with custom index:")
display(df_dict_index)

# 4. Create a DataFrame df_numpy from a NumPy array, providing custom index and columns parameters. Display the DataFrame.
numpy_data = np.random.randint(10, 100, size=(4, 3))
numpy_index = ['row1', 'row2', 'row3', 'row4']
numpy_columns = ['colA', 'colB', 'colC']
df_numpy = pd.DataFrame(numpy_data, index=numpy_index, columns=numpy_columns)
print("\n4. DataFrame from NumPy array with custom index and columns:")
display(df_numpy)

# 5. Create a nested dictionary nested_data.
nested_data = {
    'apple': {'color': 'red', 'taste': 'sweet'},
    'banana': {'color': 'yellow', 'taste': 'sweet'},
    'lemon': {'color': 'yellow', 'taste': 'sour'}
}
print("\n5. Created nested dictionary 'nested_data'.")

# 6. Create a DataFrame df_nested_dict from nested_data. Display the DataFrame.
df_nested_dict = pd.DataFrame(nested_data)
print("\n6. DataFrame created from a nested dictionary:")
display(df_nested_dict)

1. DataFrame created from a dictionary:

          City  Population State
0     New York     8419000    NY
1  Los Angeles     3980000    CA
2      Chicago     2716000    IL
3      Houston     2320000    TX
4      Phoenix     1660000    AZ

2. DataFrame from dictionary with specified columns:

          City State
0     New York    NY
1  Los Angeles    CA
2      Chicago    IL
3      Houston    TX
4      Phoenix    AZ

3. DataFrame from dictionary with custom index:

          City  Population State
A     New York     8419000    NY
B  Los Angeles     3980000    CA
C      Chicago     2716000    IL
D      Houston     2320000    TX
E      Phoenix     1660000    AZ

4. DataFrame from NumPy array with custom index and columns:

      colA  colB  colC
row1    65    55    23
row2    90    48    34
row3    28    76    28
row4    40    79    67

5. Created nested dictionary 'nested_data'.

6. DataFrame created from a nested dictionary:

       apple  banana   lemon
color    red  yellow  yellow
taste  sweet   sweet    sour

## Final Task

### Subtask:
Review all the new examples and ensure they are clear and cover the discussed topics comprehensively.

## Summary:

### Data Analysis Key Findings

*   **DataFrame Creation Flexibility**: Pandas DataFrames can be initialized from diverse data structures.
    *   **From Dictionaries**: Using a dictionary where keys are column names and values are lists or Series, Pandas automatically assigns a default `RangeIndex`.
    *   **Customization during Creation**: Both columns and row indices can be explicitly specified and ordered during DataFrame creation from a dictionary.
    *   **From NumPy Arrays**: DataFrames can be built from NumPy arrays, allowing for separate specification of row indices and column names.
    *   **From Nested Dictionaries**: Nested dictionaries can be directly converted, where outer keys become column names and inner keys become row indices, with missing values automatically filled with `NaN`.
*   **Element Selection**: Data can be accessed flexibly:
    *   Individual columns are selected like dictionary keys or attributes.
    *   Rows are accessed by integer position using `.iloc[]`.
    *   Specific cell values are accessed by combining column and row indexing.
*   **Value Assignment and Modification**: DataFrames allow dynamic changes:
    *   Index and column names can be assigned.
    *   New columns can be added by assigning a scalar or a Series.
    *   Existing columns and individual cell values can be updated.
*   **Membership and Filtering**:
    *   The `isin()` method identifies values within the DataFrame, returning a boolean DataFrame for subsequent filtering.
    *   Conditional expressions on column values enable filtering rows to create subsets of the DataFrame.
*   **Deletion of Data**:
    *   Columns can be removed using the `del` keyword or the `drop()` method with `axis=1`.
    *   Rows can be removed using the `drop()` method by specifying their labels.
*   **Transposition**: The `.T` attribute efficiently swaps rows and columns.
*   **Index Objects**:
    *   Index objects are immutable.
    *   Methods like `is_unique`, `idxmin()`, and `idxmax()` provide useful index information.
*   **Reindexing**: The `reindex()` method allows creating a new DataFrame or Series with a revised index, enabling reordering and filling missing values using methods like `'ffill'` or `'bfill'`.
*   **Arithmetic Operations and Alignment**:
    *   Operations between Series and DataFrames automatically align data based on common labels. Non-matching labels result in `NaN` values.
    *   Flexible methods like `.add()`, `.sub()`, etc., allow specifying a `fill_value` for `NaN` entries during alignment.
    *   Operations between a DataFrame and a Series align the Series' index with the DataFrame's columns by default, broadcasting across rows.
*   **Function Application**:
    *   NumPy universal functions (`ufuncs`) can be applied element-wise.
    *   The `apply()` method enables custom functions (lambda or user-defined) to be executed column-wise (default) or row-wise (`axis=1`).
*   **Statistical Functions**: Built-in methods like `mean()`, `sum()`, and `describe()` provide descriptive statistics, operating column-wise by default but adjustable to row-wise.
*   **Sorting and Ranking**:
    *   `sort_index()` sorts by index labels, `sort_values()` sorts by column values.
    *   `rank()` assigns ranks to elements based on their values.
*   **Correlation and Covariance**: `corr()` and `cov()` calculate correlation and covariance between Series or across DataFrame columns, while `corrwith()` correlates a DataFrame with a Series or another DataFrame.
*   **NaN Value Handling**:
    *   Missing values can be explicitly introduced using `np.nan` or `None`.
    *   `isnull()` and `notnull()` identify missing data.
    *   `dropna()` removes rows/columns with `NaN`s, with options to remove only if all values are `NaN` (`how='all'`).
    *   `fillna()` replaces `NaN`s with a specified scalar or different values per column.
*   **Hierarchical Indexing**:
    *   MultiIndex allows DataFrames/Series to have multiple levels of indices.
    *   Data selection, `unstack()` (index to columns) and `stack()` (columns to index), `swaplevel()` (reorder levels), `sort_index(level=...)` (sort by specific level), and `groupby(level=...).sum()` (summary statistics by level) are key functionalities for working with hierarchical data.

### Insights or Next Steps

*   **Insight**: Pandas DataFrames offer a highly versatile and powerful toolkit for data manipulation, covering everything from basic creation and selection to advanced features like hierarchical indexing and robust missing data handling, making it indispensable for data analysis workflows.
*   **Next Step**: Apply these fundamental and advanced DataFrame functionalities to a real-world dataset to solidify understanding and practice solving common data cleaning, transformation, and analysis challenges.

# Task
Okay, I will proceed with the correction.
Let's fix the `SyntaxError` in cell `cje1xY3TFhvp`.

```python
frame.mean(axis=1)
```

## Correct the SyntaxError in the cell.

### Subtask:
Modify the code to pass `axis=1` as an argument directly to the `frame.mean()` method using the correct syntax: `frame.mean(axis=1)`.

## Summary:

### Data Analysis Key Findings
*   A `SyntaxError` related to the `frame.mean()` method was identified and corrected.
*   The error stemmed from incorrect syntax when passing the `axis` argument, which was resolved by ensuring `axis=1` was directly within the method call.

### Insights or Next Steps
*   Always ensure correct syntax for method arguments, paying close attention to parameter names and value assignment.
*   Refer to library documentation for precise method signatures if encountering syntax-related errors.

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('titanic.csv')

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
data.shape

(891, 12)

# Task
## Data Overview

### Subtask:
Display the first few rows of the `data` DataFrame, check its data types, and get a summary of non-null values using `head()` and `info()`.

### Reasoning:
The first step in any data analysis is to understand the structure and basic characteristics of the dataset. Using `head()` will provide a quick glimpse into the data, showing the first few rows and column names. `info()` is crucial for understanding the data types of each column and identifying any missing (non-null) values, which is essential for subsequent data cleaning and preprocessing steps.

```python
print("First 5 rows of the DataFrame:")
display(data.head())

print("\nDataFrame Info (data types and non-null values):")
data.info()
```

## Data Overview

### Subtask:
Display the first few rows of the `data` DataFrame, check its data types, and get a summary of non-null values using `head()` and `info()`.

**Reasoning**:
The subtask requires displaying the first few rows, checking data types, and getting a summary of non-null values of the `data` DataFrame. The code block will perform these actions using `data.head()` and `data.info()`.

In [ ]:
print("First 5 rows of the DataFrame:")
display(data.head())

print("\nDataFrame Info (data types and non-null values):")
data.info()

First 5 rows of the DataFrame:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

DataFrame Info (data types and non-null values):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Missing Values Analysis

### Subtask:
Calculate and display the sum of missing values for each column in the 'data' DataFrame using `isnull().sum()`.

**Reasoning**:
The subtask requires calculating and displaying the sum of missing values for each column in the `data` DataFrame. The `isnull().sum()` method is ideal for this purpose.

In [ ]:
print("Sum of missing values for each column:")
display(data.isnull().sum())

Sum of missing values for each column:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

## Descriptive Statistics

### Subtask:
Generate descriptive statistics for numerical columns in the 'data' DataFrame using `describe()`.

**Reasoning**:
The subtask requires generating descriptive statistics for numerical columns in the `data` DataFrame. The `describe()` method is designed for this purpose.

In [ ]:
print("Descriptive statistics for numerical columns:")
display(data.describe())

Descriptive statistics for numerical columns:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Categorical Feature Analysis

### Subtask:
Analyze the distribution of categorical features ('Survived', 'Pclass', 'Sex', 'Embarked') using `value_counts()`.

**Reasoning**:
The subtask requires analyzing the distribution of specified categorical features using `value_counts()`. This code block will iterate through the categorical columns, print a header, and display the value counts for each.

In [ ]:
categorical_cols = ['Survived', 'Pclass', 'Sex', 'Embarked']

for col in categorical_cols:
    print(f"\nDistribution of {col}:")
    display(data[col].value_counts())

Distribution of Survived:

Survived
0    549
1    342
Name: count, dtype: int64

Distribution of Pclass:

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

Distribution of Sex:

Sex
male      577
female    314
Name: count, dtype: int64

Distribution of Embarked:

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

## Analyze Survival by Categorical Features

### Subtask:
Examine survival rates across 'Sex', 'Pclass', and 'Embarked' using `groupby()` and `mean()` on the 'Survived' column.

**Reasoning**:
The subtask requires calculating survival rates grouped by 'Sex', 'Pclass', and 'Embarked'. I will use `groupby()` on each specified categorical column and then apply `mean()` to the 'Survived' column to get the average survival rate for each category.

In [ ]:
print("Survival Rates by Sex:")
display(data.groupby('Sex')['Survived'].mean())

print("\nSurvival Rates by Pclass:")
display(data.groupby('Pclass')['Survived'].mean())

print("\nSurvival Rates by Embarked:")
display(data.groupby('Embarked')['Survived'].mean())

Survival Rates by Sex:

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Survival Rates by Pclass:

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Survival Rates by Embarked:

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [ ]:
data.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [ ]:
data[['Age','Fare']].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [ ]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
np_data=data.to_numpy()
np_data

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [ ]:
data.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
PassengerId,1,2,3,4,5,6,7,8,9,10,...,882,883,884,885,886,887,888,889,890,891
Survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
Pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
Name,"Braund, Mr. Owen Harris","Cumings, Mrs. John Bradley (Florence Briggs Th...","Heikkinen, Miss. Laina","Futrelle, Mrs. Jacques Heath (Lily May Peel)","Allen, Mr. William Henry","Moran, Mr. James","McCarthy, Mr. Timothy J","Palsson, Master. Gosta Leonard","Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Nasser, Mrs. Nicholas (Adele Achem)",...,"Markun, Mr. Johann","Dahlberg, Miss. Gerda Ulrika","Banfield, Mr. Frederick James","Sutehall, Mr. Henry Jr","Rice, Mrs. William (Margaret Norton)","Montvila, Rev. Juozas","Graham, Miss. Margaret Edith","Johnston, Miss. Catherine Helen ""Carrie""","Behr, Mr. Karl Howell","Dooley, Mr. Patrick"
Sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
Age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0
SibSp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
Parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
Ticket,A/5 21171,PC 17599,STON/O2. 3101282,113803,373450,330877,17463,349909,347742,237736,...,349257,7552,C.A./SOTON 34068,SOTON/OQ 392076,382652,211536,112053,W./C. 6607,111369,370376
Fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75
Cabin,NaN,C85,NaN,C123,NaN,NaN,E46,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B42,NaN,C148,NaN
Embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q

In [ ]:
data[7:15]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [ ]:
data.iloc[1:3,3:7]

                                                Name     Sex   Age  SibSp
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0

In [ ]:
data.loc[100:110,['Name','Age']]

                                 Name   Age
100           Petranec, Miss. Matilda  28.0
101  Petroff, Mr. Pastcho ("Pentcho")   NaN
102         White, Mr. Richard Frasar  21.0
103        Johansson, Mr. Gustaf Joel  33.0
104    Gustafsson, Mr. Anders Vilhelm  37.0
105             Mionoff, Mr. Stoytcho  28.0
106  Salkjelsvik, Miss. Anna Kristine  21.0
107            Moss, Mr. Albert Johan   NaN
108                   Rekic, Mr. Tido  38.0
109               Moran, Miss. Bertha   NaN
110    Porter, Mr. Walter Chamberlain  47.0

In [ ]:
data[data['Age']>70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [ ]:
data[(data['Age']>60) & (data['Sex']=='female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [ ]:
data.dropna(how='any')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C