#Data Transformation

So far you have seen how to prepare data for analysis. This process in effect represents a reassembly of the data contained within a DataFrame, with possible additions by other DataFrame and removal of
unwanted parts.

Now begin with the second stage of data manipulation: the data transformation. After you arrange the form of data and their disposal within the data structure, it is important to transform their values. In fact, in this section you will see some common issues and the steps required to overcome them using functions of
the pandas library.

Some of these operations involve the presence of duplicate or invalid values, with possible removal or replacement. Other operations relate instead modifying the indexes. Other steps include handling and
processing the numerical values of the data and also of strings.

#Removing Duplicates

Duplicate rows might be present in a DataFrame for various reasons. In DataFrames of enormous size the
detection of these rows can be very problematic. Also in this case, pandas provides us with a series of tools to
analyze the duplicate data present in large data structures.

First, create a simple DataFrame with some duplicate rows.

In [ ]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],'value': [2,1,3,3,2]})
dframe

   color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

The duplicated() function applied to a DataFrame can detect the rows which appear to be duplicated. It returns a Series of Booleans where each element corresponds to a row, with True if the row is duplicated (i.e., only the other occurrences, not the first), and with False if there are no duplicates in the previous elements.

In [ ]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

The fact of having as the return value a Boolean Series can be useful in many cases, especially for the filtering. In fact, if you want to know what are the duplicate rows, just type the following:

In [ ]:
dframe[dframe.duplicated()]

   color  value
3    red      3
4  white      2

Generally, all duplicated rows are to be deleted from the DataFrame; to do that, pandas provides the drop_duplicates() function, which returns the DataFrame without duplicate rows.

#Mapping

The pandas library provides a set of functions which, as you shall see in this section, exploit mapping to perform some operations. The mapping is nothing more than the creation of a list of matches between two different values, with the ability to bind a value to a particular label or string.

To define a mapping there is no better object than dict objects.

map = {


'label1' : 'value1,

'label2' : 'value2,

...

}

The functions that you will see in this section perform specific operations but all of them are united from accepting a dict object with matches as an argument.

• replace(): replaces values

• map(): creates a new column

• rename(): replaces the index values

#Replacing Values via Mapping

Often in the data structure that you have assembled there are values that do not meet your needs. For example, the text may be in a foreign language, or may be a synonym of another value, or may not be expressed in the desired shape. In such cases, a replace operation of various values is often a necessary process.

Define, as an example, a DataFrame containing various objects and colors, including two colors that are not in English. Often during the assembly operations is likely to keep maintaining data with values in a form that is not desired.

In [ ]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'], 'color':['white','rosso','verde','black','yellow'], 'price':[5.56,4.20,1.30,0.56,2.75]})
frame

      item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

Thus to be able to replace the incorrect values in new values is necessary to define a mapping of correspondences, containing as key to replace the old values and values as the new ones.

In [ ]:
newcolors = {
... 'rosso': 'red',
... 'verde': 'green'
... }

In [ ]:
#Now the only thing you can do is to use the replace() function with the mapping as an argument.
frame.replace(newcolors)

      item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

As you can see from the result, the two colors have been replaced with the correct values within the DataFrame. A common case, for example, is the replacement of the NaN values with another value, for example 0. Also here you can use the replace(), which performs its job very well.

In [ ]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [ ]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

#Adding Values via Mapping

In the previous example, you have seen the case of the substitution of values through a mapping of correspondences. In this case you continue to exploit the mapping of values with another example. In this case you are exploiting mapping to add values in a column depending on the values contained in another.

The mapping will always be defined separately.

In [ ]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
... 'color':['white','red','green','black','yellow']})
frame

      item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

Let’s suppose you want to add a column to indicate the price of the item shown in the DataFrame.

Before you do this, it is assumed that you have a price list available somewhere, in which the price for each type of item is described. Define then a dict object that contains a list of prices for each type of item.

In [ ]:
price = {
... 'ball' : 5.56,
... 'mug' : 4.20,
... 'bottle' : 1.30,
... 'scissors' : 3.41,
... 'pen' : 1.30,
... 'pencil' : 0.56,
... 'ashtray' : 2.75
... }

The map() function applied to a Series or to a column of a DataFrame accepts a function or an object containing a dict with mapping. So in your case you can apply the mapping of the prices on the column item, making sure to add a column to the price data frame.

In [ ]:
frame['price'] = frame['item'].map(price)
frame

      item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

#Rename the Indexes of the Axes

In a manner very similar to what you saw for the values contained within the Series and the DataFrame, even the axis label can be transformed in a very similar way using the mapping. So to replace the label indexes, pandas provides the rename() function, which takes the mapping as argument, that is, a dict object.

In [ ]:
frame

      item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [ ]:
reindex = {
... 0: 'first',
... 1: 'second',
... 2: 'third',
... 3: 'fourth',
... 4: 'fifth'}
frame.rename(reindex)

           item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

As you can see, by default, the indexes are renamed. If you want to rename columns you must use the columns option. Thus this time you assign various mapping explicitly to the two index and columns options.

In [ ]:
recolumn = {'item':'object','price': 'value'}
frame.rename(index=reindex, columns=recolumn)

         object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

Also here, for the simplest cases in which you have a single value to be replaced, it can further explicate the arguments passed to the function of avoiding having to write and assign many variables.

In [ ]:
frame.rename(index={1:'first'}, columns={'item':'object'})

        object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

So far you have seen that the rename() function returns a DataFrame with the changes, leaving unchanged the original DataFrame. If you want the changes to take effect on the object on which you call the
function, you will set the inplace option to True.

In [ ]:
frame.rename(columns={'item':'object'}, inplace=True)
frame

    object   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

#Discretization and Binning

A more complex process of transformation that you will see in this section is discretization. Sometimes
it can happen, especially in some experimental cases, to handle large quantities of data generated in
sequence. To carry out an analysis of the data, however, it is necessary to transform this data into discrete
categories, for example, by dividing the range of values of such readings in smaller intervals and counting
the occurrence or statistics within each of them. Another case might be to have a huge amount of samples
due to precise readings on a population. Even here, to facilitate analysis of the data it is necessary to divide
the range of values into categories and then analyze the occurrences and statistics related to each of them.

In [ ]:
#In your case, for example, you may have a reading of an experimental value between 0 and 100. These data are collected in a list.
import pandas as pd
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]

You know that the experimental values have a range from 0 to 100; therefore you can uniformly divide this interval, for example, into four equal parts, i.e., bins. The first contains the values between 0 and 25, the second between 26 and 50, the third between 51 and 75, and the last between 76 and 100.

To do this binning with pandas, first you have to define an array containing the values of separation of bin

In [ ]:
bins = [0,25,50,75,100]

Then there is a special function called cut() and apply it to the array of results also passing the bins.

In [ ]:
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

The object returned by the cut() function is a special object of Categorical type. You can consider it as an array of strings indicating the name of the bin. Internally it contains a levels array indicating the names of the different internal categories and a labels array that contains a list of numbers equal to the elements of results (i.e., the array subjected to binning). The number corresponds to the bin to which the corresponding element of results is assigned.

In [ ]:
cat.categories

IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]], dtype='interval[int64, right]')

In [ ]:
cat.codes

array([0, 1, 2, 2, 1, 3, 3, 0, 0, 2, 2, 1, 3, 0, 1, 3, 3], dtype=int8)

Finally to know the occurrences for each bin, that is, how many results fall into each category, you have to use the value_counts() function.

In [ ]:
pd.value_counts(cat)

/tmp/ipykernel_8066/764800318.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cat)

(75, 100]    5
(0, 25]      4
(25, 50]     4
(50, 75]     4
Name: count, dtype: int64

As you can see, each class has the lower limit with a bracket and the upper limit with a parenthesis. This notation is consistent with mathematical notation that is used to indicate the intervals. If the bracket is square, the number belongs to the range (limit closed), and if it is round the number does not belong to the
interval (limit open).

You can give names to various bins by calling them first in an array of strings and then assigning to the labels options inside the cut() function that you have used to create the Categorical object.

In [ ]:
bin_names = ['unlikely','less likely','likely','highly likely']
pd.cut(results, bins, labels=bin_names)

['unlikely', 'less likely', 'likely', 'likely', 'less likely', ..., 'highly likely', 'unlikely', 'less likely', 'highly likely', 'highly likely']
Length: 17
Categories (4, object): ['unlikely' < 'less likely' < 'likely' < 'highly likely']

If the cut() function is passed as an argument to an integer instead of explicating the bin edges, this will
divide the range of values of the array in many intervals as specified by the number.

The limits of the interval will be taken by the minimum and maximum of the sample data, namely, the array subjected to binning.

In [ ]:
pd.cut(results, 5)

[(2.904, 22.2], (22.2, 41.4], (60.6, 79.8], (41.4, 60.6], (22.2, 41.4], ..., (79.8, 99.0], (22.2, 41.4], (41.4, 60.6], (79.8, 99.0], (79.8, 99.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.904, 22.2] < (22.2, 41.4] < (41.4, 60.6] <
                                           (60.6, 79.8] < (79.8, 99.0]]

In addition to cut(), pandas provides another method for binning: qcut(). This function divides the sample directly into quintiles. In fact, depending on the distribution of the data sample, using cut() rightly you will have a different number of occurrences for each bin. Instead qcut() will ensure that the number of occurrences for each bin is equal, but the edges of each bin to vary.

In [ ]:
quintiles = pd.qcut(results, 5)
quintiles

[(2.999, 24.0], (24.0, 46.0], (62.6, 87.0], (46.0, 62.6], (24.0, 46.0], ..., (62.6, 87.0], (2.999, 24.0], (46.0, 62.6], (87.0, 99.0], (62.6, 87.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.999, 24.0] < (24.0, 46.0] < (46.0, 62.6] <
                                           (62.6, 87.0] < (87.0, 99.0]]

In [ ]:
pd.value_counts(quintiles)

/tmp/ipykernel_8066/194218986.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quintiles)

(2.999, 24.0]    4
(62.6, 87.0]     4
(24.0, 46.0]     3
(46.0, 62.6]     3
(87.0, 99.0]     3
Name: count, dtype: int64

As you can see, in the case of quintiles, the intervals bounding the bin differ from those generated by the cut() function. Moreover, if you look at the occurrences for each bin will find that qcut() tried to standardize the occurrences for each bin, but in the case of quintiles, the first two bins have an occurrence in more because the number of results is not divisible by five.

#Detecting and Filtering Outliers

During the data analysis, the need to detect the presence of abnormal values within a data structure often
arises. By way of example, create a DataFrame with three columns from 1,000 completely random values:

In [ ]:
import pandas as pd
import numpy as np
randframe = pd.DataFrame(np.random.randn(1000,3))
randframe

            0         1         2
0    0.679407  1.645278 -0.009970
1   -1.150774  0.607293  1.893438
2   -0.863301 -1.690127 -1.457042
3    0.549067 -0.251445  0.249913
4   -0.036832  0.032380 -1.266768
..        ...       ...       ...
995 -0.791559  0.089042  1.410616
996  2.127160  0.033303 -0.252911
997  0.216337  2.090977  0.471819
998  1.130751  1.543460 -1.363925
999 -0.174479  0.045430  0.195563

[1000 rows x 3 columns]

In [ ]:
#With the describe() function you can see the statistics for each column.
randframe.describe()

                 0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.034650     0.029148     0.039900
std       0.980612     0.961880     0.978288
min      -2.805398    -4.688879    -2.795089
25%      -0.693129    -0.607587    -0.633868
50%      -0.018722     0.029846     0.006330
75%       0.619828     0.703571     0.716064
max       3.139028     2.786599     3.068305

In [ ]:
#For example, you might consider outliers those that have a value greater than three times the standard deviation. To have only the standard deviation of each column of the DataFrame, use the std() function.
randframe.std()

0    0.980612
1    0.961880
2    0.978288
dtype: float64

In [ ]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(axis=1)]

            0         1         2
55   3.009623 -0.447517 -0.621071
80   1.747305 -0.043908  3.068305
275 -0.744976 -3.320407  0.927363
636  3.139028  0.033457  0.488334
786 -0.681257 -1.098486  2.985798
904  0.648758 -1.508276  2.974401
962 -0.915144 -4.688879 -2.558284

Certainly! Let's break down the code randframe[(np.abs(randframe) > (3*randframe.std())).any(axis=1)] and what the output means:

randframe.std(): This calculates the standard deviation for each column in your randframe DataFrame. The standard deviation measures the amount of variation or dispersion of a set of values.

3 * randframe.std(): This multiplies each column's standard deviation by 3. This value serves as our threshold for identifying an outlier.

np.abs(randframe): This calculates the absolute value of each element in the randframe. We do this because an outlier can be significantly higher or significantly lower than the mean.

np.abs(randframe) > (3 * randframe.std()): This is the core condition. It compares the absolute value of each element in randframe to three times the standard deviation of its respective column. This operation returns a new DataFrame of boolean values (True/False), where True indicates that an element is greater than 3 times its column's standard deviation.

.any(axis=1): This is applied to the boolean DataFrame from the previous step. It checks each row (axis=1) and returns True if any element in that row satisfies the condition (i.e., if at least one value in the row is an outlier). If no element in a row is an outlier, it returns False.

randframe[...]: Finally, this boolean Series (from the .any(axis=1) step) is used to filter the original randframe DataFrame. Only the rows for which .any(axis=1) returned True (meaning they contain at least one outlier) are included in the final output.

In summary, the output DataFrame shows all the rows from your randomly generated data (randframe) that contain at least one value that is considered an outlier, defined as being more than three standard deviations away from the mean of its respective column. These are the data points that are significantly different from the rest of the data in your DataFrame.

What can I help you build?
Gemini 2.5 Flash
Gemini can make mistakes, so double-check it and use code with caution. Learn more

### Count of Outlier Rows

To get the number of outlier rows, we can simply find the number of rows in the DataFrame resulting from the outlier detection filter.

In [ ]:
outlier_rows = randframe[(np.abs(randframe) > (3*randframe.std())).any(axis=1)]
print(f"Number of outlier rows identified: {outlier_rows.shape[0]}")

Number of outlier rows identified: 7

#Permutation

The operations of permutation (random reordering) of a Series or the rows of a DataFrame are easy to do using the numpy.random.permutation() function.

For this example, create a DataFrame containing integers in ascending order.

In [ ]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [ ]:
#Now create an array of five integers from 0 to 4 arranged in random order with the permutation() function. This will be the new order in which to set the values of a row of DataFrame.
new_order = np.random.permutation(5)
new_order

array([4, 1, 0, 3, 2])

In [ ]:
#Now apply it to the DataFrame on all lines, using the take() function.
nframe.take(new_order)

    0   1   2   3   4
4  20  21  22  23  24
1   5   6   7   8   9
0   0   1   2   3   4
3  15  16  17  18  19
2  10  11  12  13  14

As you can see, the order of the rows has been changed; now the indices follow the same order as indicated in the new_order array.

You can submit even a portion of the entire DataFrame to a permutation. It generates an array that has a sequence limited to a certain range, for example, in our case from 2 to 4.

In [ ]:
new_order = [3,4,2]
nframe.take(new_order)

    0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24
2  10  11  12  13  14

#Random Sampling

You have just seen how to extract a portion of the DataFrame determined by subjecting it to permutation.

Sometimes, when you have a huge DataFrame, you may have the need to sample it randomly, and the quickest way to do this is by using the np.random.randint() function.

In [ ]:
sample = np.random.randint(0, len(nframe), size=3)
sample

array([2, 2, 0])

In [ ]:
nframe.take(sample)

    0   1   2   3   4
2  10  11  12  13  14
2  10  11  12  13  14
0   0   1   2   3   4

The last executed cell, nframe.take(sample), performed random sampling on your nframe DataFrame. Here's a breakdown of the outcome:

sample = np.random.randint(0, len(nframe), size=3): This line first determined the number of rows in nframe using len(nframe) (which is 5). Then, np.random.randint(0, 5, size=3) generated an array of 3 random integers, where each integer is between 0 (inclusive) and 5 (exclusive). These integers represent row indices.

In your specific execution, sample turned out to be array([2, 2, 0]). This means the sampling selected the row at index 2 twice, and the row at index 0 once.
nframe.take(sample): This function uses the sample array to select rows from the nframe DataFrame. For each number in sample, nframe.take() retrieves the row corresponding to that index. Since the index 2 appeared twice in sample, the row at index 2 from nframe is included twice in the output.

#String Manipulation

Python is a popular language thanks to its ease of use in the processing of strings and text. Most operations
can easily be made by using built-in functions provided by Python. For more complex cases of matching and
manipulation, it is necessary the use of regular expressions.

#Built-in Methods for Manipulation of Strings

In many cases you have composite strings in which you would like to separate the various parts and then assign them to the correct variables. The split() function allows us to separate parts of a text, taking as a reference point a separator, for example a comma.

In [ ]:
text = '16 Bolton Avenue , Boston'
text.split(',')

['16 Bolton Avenue ', ' Boston']

As we can see in the first element, you have a string with a space character at the end. To overcome this problem and often a frequent problem, you have to use the split() function along with the strip() function
that takes care of doing the trim of whitespace (including newlines).

In [ ]:
tokens = [s.strip() for s in text.split(',')]
tokens

['16 Bolton Avenue', 'Boston']

The result is an array of strings. If the number of elements is small and always the same, a very interesting way to make assignments may be this:

In [ ]:
address, city = [s.strip() for s in text.split(',')]
address

'16 Bolton Avenue'

In [ ]:
city

'Boston'

So far you have seen how to split a text into parts, but often you also need the opposite, namely concatenating various strings between them to form a more extended text.

The most intuitive and simple way is to concatenate the various parts of the text with the operator '+'.

In [ ]:
address + ',' + city

'16 Bolton Avenue,Boston'

This can be useful when you have only two or three strings to be concatenated. If the parts to be concatenated are much more, a more practical approach in this case will be to use the join() function assigned to the separator character, with which you want to join the various strings between them.

In [ ]:
strings = ['A+','A','A-','B','BB','BBB','C+']
';'.join(strings)

'A+;A;A-;B;BB;BBB;C+'

Another category of operations that can be performed on the string is the search for pieces of text in them, i.e., substrings. Python provides, in this respect, the keyword which represents the best way of
detecting substrings.

In [ ]:
'Boston' in text

True

However, there are two functions that could serve to this purpose: index() and find().

In [ ]:
text.index('Boston')

19

In [ ]:
text.find('Boston')

19

In both cases, it returns the number of the corresponding character in the text where you have the substring. The difference in the behavior of these two functions can be seen, however, when the substring is
not found:

In [ ]:
text.index('New York')

ValueError: substring not found

In [ ]:
text.find('New York')

-1

In fact, the index() function returns an error message, and find() returns -1 if the substring is not found.
In the same area, you can know how many times a character or combination of characters (substring) occurs
within a text. The count() function provides you with this number.

In [ ]:
text.count('e')

2

In [ ]:
text.count('Avenue')

1

Another operation that can be performed on strings is the replacement or elimination of a substring (or a single character). In both cases you will use the replace()  function, where if you are prompted to replace a substring with a blank character, the operation will be equivalent to the elimination of the substring from the text.

In [ ]:
text.replace('Avenue','Street')

'16 Bolton Street , Boston'

In [ ]:
text.replace('1','')

'6 Bolton Avenue , Boston'

#Regular Expressions

The regular expressions provide a very flexible way to search and match string patterns within a text. A single
expression, generically called regex, is a string formed according to the regular expression language. There is a built-in Python module called re, which is responsible for the operation of the regex.

In [ ]:
#So first of all, when you want to make use of regular expressions, you will need to import the module.
import re

The re module provides a set of functions that can be divided into three different categories:

• pattern matching

• substitution

• splitting

Now you start with a few examples. For example, the regex for expressing a sequence of one or more whitespace characters is \s+. As you saw in the previous section, to split a text into parts through a separator character you used the split(). There is a split() function even for the re module that performs the same operations, only it is able to accept a regex pattern as the criterion of separation, which makes it
considerably more flexible.

In [ ]:
text = "This is an\t odd \n text!"
re.split('\s+', text)

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_4822/1221645109.py:2: SyntaxWarning: invalid escape sequence '\s'
  re.split('\s+', text)

['This', 'is', 'an', 'odd', 'text!']

But analyze more deeply the mechanism of re module. When you call the re.split() function, the regular expression is first compiled, then subsequently calls the split() function on the text argument. You can compile the regex function with the re.compile() function, thus obtaining a reusable object regex and so gaining in terms of CPU cycles.

This is especially true in the operations of iterative search of a substring in a set or an array of strings.

In [ ]:
regex = re.compile('\s+') #So, \s+ matches one or more consecutive whitespace characters.

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_4822/1890572334.py:1: SyntaxWarning: invalid escape sequence '\s'
  regex = re.compile('\s+')

So if you make an regex object with the compile() function, you can apply split() directly to it in the following way.

In [ ]:
regex.split(text)

['This', 'is', 'an', 'odd', 'text!']

As regards matching a regex pattern with any other business substrings in the text, you can use the findall() function. It returns a list of all the substrings in the text that meet the requirements of the regex.

For example, if you want to find in a string all the words starting with “A” uppercase, or for example, with “a” regardless whether upper- or lowercase, you need to enter what follows:

In [ ]:
text = 'This is my address: 16 Bolton Avenue, Boston'
re.findall('A\w+',text) #\w+ matches one or more consecutive word characters.

<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_4822/2605185007.py:2: SyntaxWarning: invalid escape sequence '\w'
  re.findall('A\w+',text)

['Avenue']

In [ ]:
re.findall('[A,a]\w+',text)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_4822/3917527.py:1: SyntaxWarning: invalid escape sequence '\w'
  re.findall('[A,a]\w+',text)

['address', 'Avenue']

There are two other functions related to the function findall(): match() and search(). While findall() returns all matches within a list, the function search() returns only the first match. Furthermore, the object returned by this function is a particular object:

In [ ]:
re.search('[A,a]\w+',text)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_4822/1814166908.py:1: SyntaxWarning: invalid escape sequence '\w'
  re.search('[A,a]\w+',text)

This object does not contain the value of the substring that responds to the regex pattern, but its start and end positions within the string.

In [ ]:
search = re.search('[A,a]\w+',text)
search.start()

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_4822/695835242.py:1: SyntaxWarning: invalid escape sequence '\w'
  search = re.search('[A,a]\w+',text)

11

In [ ]:
search.end()

18

In [ ]:
text[search.start():search.end()]

'address'

The match() function performs the matching only at the beginning of the string; if there is no match with the first character, it goes no further in research within the string. If you do not find any match then it
will not return any objects.

In [ ]:
re.match('[A,a]\w+',text)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_4822/69930824.py:1: SyntaxWarning: invalid escape sequence '\w'
  re.match('[A,a]\w+',text)

If match() has a response, then it returns an object identical to what you saw for the search() function.

In [ ]:
re.match('T\w+',text)

In [ ]:
match = re.match('T\w+',text)
text[match.start():match.end()]