#Dropping

Another operation that is connected to Index objects is dropping. Deleting a row or a column becomes simple, precisely due to the labels used to indicate the indexes and column names.

Also in this case, pandas provides a specific function for this operation: drop( ). This method will return a new object without the items that you want to delete.

For example, take the case where we want to remove a single item from a Series. To do this, define
generic Series 4 elements with four distinct labels.

In [ ]:
import numpy as np
import pandas as pd
ser = pd.Series(np.arange(4.), index=['red','blue','yellow','white'])
ser

red       0.0
blue      1.0
yellow    2.0
white     3.0
dtype: float64

Now, for example, you want to delete the item corresponding to the label ‘yellow’. Simply specify the label as an argument of the function drop( ) to delete it.

In [ ]:
ser.drop('yellow')

red      0.0
blue     1.0
white    3.0
dtype: float64

In [ ]:
#To remove more items, just pass an array with the corresponding labels.
ser.drop(['blue','white'])

red       0.0
yellow    2.0
dtype: float64

In [ ]:
ser

red       0.0
blue      1.0
yellow    2.0
white     3.0
dtype: float64

Regarding the DataFrame, instead, the values can be deleted by referring to the labels of both axes.
Declare the following frame by way of example.

In [ ]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
#To delete rows, just pass the indexes of the rows.
frame.drop(['blue','yellow'])

       ball  pen  pencil  paper
red       0    1       2      3
white    12   13      14     15

In [ ]:
frame.drop(['blue','yellow'], axis=0)

       ball  pen  pencil  paper
red       0    1       2      3
white    12   13      14     15

To delete columns, you always need to specify the indexes of the columns, but you must specify the
axis from which to delete the elements, and this can be done using the axis option. So to refer to the column names you should specify axis = 1.

In [ ]:
frame.drop(['pen','pencil'],axis=1)

        ball  paper
red        0      3
blue       4      7
yellow     8     11
white     12     15

In [ ]:
frame.drop(['pen','pencil'])

KeyError: "['pen', 'pencil'] not found in axis"

#Arithmetic and Data Alignment

Perhaps the most powerful feature involving the indexes in a data structure, is that pandas is able to perform the alignment of the indexes coming from two different data structures. This is especially true when you are performing an arithmetic operation between them. In fact, during these operations, not only may the indexes between the two structures be in a different order, but they also may be present in only one of the two structures.

As you can see from the examples that follow, pandas proves to be very powerful in the alignment of the indexes during these operations. For example, you can start considering two Series in which they are defined, respectively, two arrays of labels, not perfectly matching each other.

In [ ]:
s1 = pd.Series([3,2,5,1],['white','yellow','green','blue'])
s2 = pd.Series([1,4,7,2,1],['white','yellow','black','blue','brown'])

In [ ]:
s1

white     3
yellow    2
green     5
blue      1
dtype: int64

In [ ]:
s2

white     1
yellow    4
black     7
blue      2
brown     1
dtype: int64

Now among the various arithmetic operations, consider the simple sum. As you can see from the two Series just declared, some labels are present in both, while other labels are present only in one of the two. Well, when the labels are present in both operators, their values will be added, while in the opposite case, they will also be shown in the result (new series), but with the value NaN.

In [ ]:
s1 + s2

black     NaN
blue      3.0
brown     NaN
green     NaN
white     4.0
yellow    6.0
dtype: float64

In the case of the data frame, although it may appear more complex, the alignment follows the same
principle, but is carried out both for the rows and for the columns.

In [ ]:
frame1 = pd.DataFrame(np.arange(16).reshape((4,4)),
... index=['red','blue','yellow','white'],
... columns=['ball','pen','pencil','paper'])
frame2 = pd.DataFrame(np.arange(12).reshape((4,3)),
... index=['blue','green','white','yellow'],
... columns=['mug','pen','ball'])

In [ ]:
frame1

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
frame2

        mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [ ]:
frame1 + frame2

        ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

#Operations between Data Structures

Now that you have become familiar with the data structures such as Series and DataFrame and you have seen how various elementary operations can be performed on them, it’s time to go to operations involving two or more of these structures.

For example, in the previous section we saw how the arithmetic operators apply between two of these
objects. Now in this section you will deepen more the topic of operations that can be performed between two data structures.

#Flexible Arithmetic Methods

You’ve just seen how to use mathematical operators directly on the pandas data structures. The same
operations can also be performed using appropriate methods, called Flexible arithmetic methods.

• add( )

• sub( )

• div( )

• mul( )

In order to call these functions, you’ll need to use a specification different than what you’re used
to dealing with mathematical operators. For example, instead of writing a sum between two DataFrame ‘frame1 + frame2’, you’ll have to use the following format:

In [ ]:
frame1.add(frame2)

        ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [ ]:
frame2.add(frame1)

        ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [ ]:
frame1.sub(frame2)

        ball  mug  paper  pen  pencil
blue     2.0  NaN    NaN  4.0     NaN
green    NaN  NaN    NaN  NaN     NaN
red      NaN  NaN    NaN  NaN     NaN
white    4.0  NaN    NaN  6.0     NaN
yellow  -3.0  NaN    NaN -1.0     NaN

In [ ]:
frame2.sub(frame1)

        ball  mug  paper  pen  pencil
blue    -2.0  NaN    NaN -4.0     NaN
green    NaN  NaN    NaN  NaN     NaN
red      NaN  NaN    NaN  NaN     NaN
white   -4.0  NaN    NaN -6.0     NaN
yellow   3.0  NaN    NaN  1.0     NaN

In [ ]:
frame1.mul(frame2)

        ball  mug  paper   pen  pencil
blue     8.0  NaN    NaN   5.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   96.0  NaN    NaN  91.0     NaN
yellow  88.0  NaN    NaN  90.0     NaN

In [ ]:
frame2.mul(frame1)

        ball  mug  paper   pen  pencil
blue     8.0  NaN    NaN   5.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   96.0  NaN    NaN  91.0     NaN
yellow  88.0  NaN    NaN  90.0     NaN

In [ ]:
frame1.div(frame2)

            ball  mug  paper       pen  pencil
blue    2.000000  NaN    NaN  5.000000     NaN
green        NaN  NaN    NaN       NaN     NaN
red          NaN  NaN    NaN       NaN     NaN
white   1.500000  NaN    NaN  1.857143     NaN
yellow  0.727273  NaN    NaN  0.900000     NaN

In [ ]:
frame2.div(frame1)

            ball  mug  paper       pen  pencil
blue    0.500000  NaN    NaN  0.200000     NaN
green        NaN  NaN    NaN       NaN     NaN
red          NaN  NaN    NaN       NaN     NaN
white   0.666667  NaN    NaN  0.538462     NaN
yellow  1.375000  NaN    NaN  1.111111     NaN

As you can see the results are the same as what you’d get using the addition operator ‘+’. You can also note that if the indexes and column names differ greatly from one series to another, you’ll find yourself with a new data frame full of NaN values. You’ll see later in this chapter how to handle this kind of data.

#Operations between DataFrame and Series

Coming back to the arithmetic operators, pandas allows you to make transactions even between different structures as for example, a DataFrame and a Series. For example, we define these two structures in the
following way.

In [ ]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
... index=['red','blue','yellow','white'],
... columns=['ball','pen','pencil','paper'])
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
ser = pd.Series(np.arange(4), index=['ball','pen','pencil','paper'])
ser

ball      0
pen       1
pencil    2
paper     3
dtype: int64

The two newly defined data structures have been created specifically so that the indexes of Series match with the names of the columns of the DataFrame. This way, you can apply a direct operation.

In [ ]:
frame - ser

        ball  pen  pencil  paper
red        0    0       0      0
blue       4    4       4      4
yellow     8    8       8      8
white     12   12      12     12

As you can see, the elements of the series are subtracted from the values of the data frame
corresponding to the same index on the column. The value is subtracted for all values of the column,
regardless of their index.

If an index is not present in one of the two data structures, the result will be a new column with that index only that all its elements will be NaN.

In [ ]:
ser['mug'] = 9
ser

ball      0
pen       1
pencil    2
paper     3
mug       9
dtype: int64

In [ ]:
frame - ser

        ball  mug  paper  pen  pencil
red        0  NaN      0    0       0
blue       4  NaN      4    4       4
yellow     8  NaN      8    8       8
white     12  NaN     12   12      12

#Function Application and Mapping

##Functions by Element

The pandas library is built on the foundations of NumPy, and then extends many of its features adapting them to new data structures as Series and DataFrame. Among these are the universal functions, called ufunc. This class of functions is particular because it operates by element in the data structure.

In [ ]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
... index=['red','blue','yellow','white'],
... columns=['ball','pen','pencil','paper'])
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
#For example you could calculate the square root of each value within the data frame, using the NumPy np.sqrt().
np.sqrt(frame)

            ball       pen    pencil     paper
red     0.000000  1.000000  1.414214  1.732051
blue    2.000000  2.236068  2.449490  2.645751
yellow  2.828427  3.000000  3.162278  3.316625
white   3.464102  3.605551  3.741657  3.872983

#Functions by Row or Column

The application of the functions is not limited to the ufunc functions, but also includes those defined by the user. The important thing is that they operate on a one-dimensional array, giving a single number for result.

For example, we can define a lambda function that calculates the range covered by the elements in an array.

In [ ]:
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
f = lambda x: x.max() - x.min()
#It is possible to define the function also in this way:

def f(x):
  return x.max() - x.min()

#Using the apply( ) function you can apply the function just defined on the DataFrame.
frame.apply(f)

ball      12
pen       12
pencil    12
paper     12
dtype: int64

In [ ]:
#The result, however, this time it is only one value for the column, but if you prefer to apply the function by row instead of by column, you have to specify the axis option set to 1.
frame.apply(f, axis=1)

red       3
blue      3
yellow    3
white     3
dtype: int64

It is not mandatory that the method apply( ) returns a scalar value. It can also return a Series. A useful case would be to extend the application to many functions simultaneously. In this case we will have two or more values for each feature applied. This can be done by defining a function in the following manner:

In [ ]:
def f(x):
  return pd.Series([x.min(), x.max()], index=['min','max'])

Then, apply the function as before. But in this case as an object returned you get a DataFrame and no longer a Series, in which there will be as many rows as the values returned by the function.

In [ ]:
frame.apply(f)

     ball  pen  pencil  paper
min     0    1       2      3
max    12   13      14     15

In [ ]:
frame.apply(f,axis=1)

        min  max
red       0    3
blue      4    7
yellow    8   11
white    12   15

#Statistics Functions

However, the majority of the statistical functions for arrays are still valid for DataFrame, so the use of the apply( ) function is no longer necessary. For example, functions such as sum( ) and mean( ) can calculate the sum and the average, respectively, of the elements contained within a DataFrame.

In [ ]:
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
frame.mean()

ball      6.0
pen       7.0
pencil    8.0
paper     9.0
dtype: float64

In [ ]:
frame.mean(axis=1)

red        1.5
blue       5.5
yellow     9.5
white     13.5
dtype: float64

In [ ]:
frame.sum()

ball      24
pen       28
pencil    32
paper     36
dtype: int64

In [ ]:
frame.sum(axis=1)

red        6
blue      22
yellow    38
white     54
dtype: int64

In [ ]:
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
frame.describe()

            ball        pen     pencil      paper
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

In [ ]:
frame.T.describe()

            red      blue     yellow      white
count  4.000000  4.000000   4.000000   4.000000
mean   1.500000  5.500000   9.500000  13.500000
std    1.290994  1.290994   1.290994   1.290994
min    0.000000  4.000000   8.000000  12.000000
25%    0.750000  4.750000   8.750000  12.750000
50%    1.500000  5.500000   9.500000  13.500000
75%    2.250000  6.250000  10.250000  14.250000
max    3.000000  7.000000  11.000000  15.000000

#Sorting and Ranking

Another fundamental operation that makes use of the indexing is sorting. Sorting the data is often a necessity and it is very important to be able to do easily. Pandas provides the sort_index( ) function that returns a new object which is identical to the start, but in which the elements are ordered.

In [ ]:
ser = pd.Series([5,0,3,8,4], index=['red','blue','yellow','white','green'])
ser

red       5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [ ]:
ser.sort_index()

blue      0
green     4
red       5
white     8
yellow    3
dtype: int64

In [ ]:
ser.sort_index(ascending=False)

yellow    3
white     8
red       5
green     4
blue      0
dtype: int64

As regards the DataFrame, the sorting can be performed independently on each of its two axes. So
if you want to order by row following the indexes, just continue to use the function sort_index( ) without arguments as you’ve seen before, or if you prefer to order by columns, you will need to use the axis options set to 1.

In [ ]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
... index=['red','blue','yellow','white'],
... columns=['ball','pen','pencil','paper'])
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
frame.sort_index()

        ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [ ]:
frame.sort_index(axis=1)

        ball  paper  pen  pencil
red        0      3    1       2
blue       4      7    5       6
yellow     8     11    9      10
white     12     15   13      14

So far you have learned how to sort the values according to the indexes. But very often you may need to sort the values contained within the data structure. In this case you have to differentiate depending on whether you have to sort the values of a Series or a DataFrame.

If you want to order the series, you will use the sort_values( ) function.

In [ ]:
ser.sort_values()

blue      0
yellow    3
green     4
red       5
white     8
dtype: int64

In [ ]:
ser.sort_values(ascending=False)

white     8
red       5
green     4
yellow    3
blue      0
dtype: int64

If you need to order the values in a DataFrame, you will use the sort_values( ) function seen previously but with the by option. Then you have to specify the name of the column on which to sort.

In [ ]:
frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [ ]:
frame.sort_values(by='pen')

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

If the criteria of sorting will be based on two or more columns, you can assign an array containing the names of the columns to the by option.

In [ ]:
frame.sort_values(by=['pen','pencil'])

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

The ranking is an operation closely related to sorting. It mainly consists of assigning a rank (that is, a value that starts at 0 and then increase gradually) to each element of the series. The rank will be assigned starting from the lowest value to the highest value.

In [ ]:
ser

red       5
blue      0
yellow    3
white     8
green     4
dtype: int64

In [ ]:
ser.rank()

red       4.0
blue      1.0
yellow    2.0
white     5.0
green     3.0
dtype: float64

The rank can also be assigned in the order in which the data are already in the data structure (without a sorting operation). In this case, just add the method option with the ‘first’ value assigned.

In [1]:
ser.rank(method='first')

NameError: name 'ser' is not defined

In [ ]:
ser.rank(ascending=False)