#PANDAS in Depth: Data Manipulation

Once you have the data in DataFrame format, they are ready to be manipulated. The manipulation of the data has the purpose of preparing the data so that they can be more easily subjected to analysis. In fact, their
manipulation will depend a lot on purposes of those who must carry out the analysis, and it will be performed for making more explicit the information you are looking for. Especially in preparation for the next phase, the
data must be ready to the data visualization.

The three phases of data manipulation are

• Data preparation

• Data transformation

• Data aggregation

#Data Preparation

Before you start manipulating data itself, it is necessary to prepare the data and assemble them in the form of data structures such that they can be manipulated later with the tools made available by the pandas library.

The different procedures for data preparation are listed below.

• loading

• assembling

              • merging

              • concatenating

              • combining

• reshaping (pivoting)

• removing

In the loading phase, there is also that part of the preparation which concerns the conversion from many different formats into a data structure such as DataFrame. But even after you have gotten the data, probably from different sources and formats, and unified it into a DataFrame, you will need to perform further operations of preparation.

The data contained in the pandas objects can be assembled together in different ways:

• Merging—the pandas.merge( ) function connects the rows in a DataFrame based on one or more keys.

• Concatenating—the pandas.concat( ) function concatenates the objects along an axis.

• Combining—the pandas.DataFrame.combine_first( ) function is a method that
allows you to connect overlapped data in order to fill in missing values in a data structure by taking data from another structure.

Furthermore, part of the preparation process is also pivoting, which consists of the exchange between rows and columns.

#Merging

The merging operation, which corresponds to the JOIN operation for those who are familiar with SQL, consists of a combination of data through the connection of rows using one or more keys.

In fact, anyone working with relational databases usually makes use of the JOIN query with SQL to get data from different tables using some reference values (keys) shared between them. On the basis of these keys it is possible to obtain new data in a tabular form as the result of the combination of other tables. This operation with the library pandas is called merging, and merge() is the function to perform this kind of
operation.

First, you have to import the pandas library and define two DataFrame that will serve you as examples
for this section.

In [22]:
import numpy as np
import pandas as pd
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'], 'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

        id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [23]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],'color': ['white','red','red','black']})
frame2

       id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [24]:
pd.merge(frame1,frame2)

       id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

As you can see from the result, the returned DataFrame consists of all rows that have an ID in common between the two DataFeame. In addition to the common column, the columns from both the first and the second DataFrame are added.

In this case you used the merge( ) function without specifying any column explicitly. In fact, in most cases you need to decide which is the column on which to base the merging.

To do this, add the on option with the column name as the key for the merging.

In [25]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],'color': ['white','red','red','black','green'],'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [26]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],'brand': ['OMG','POD','ABC','POD']})
frame2

       id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

Now in this case you have two DataFrame having columns with the same name. So if you launch a merging you do not get any results.

In [27]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

So it is necessary to explicitly define the criterion of merging that pandas must follow, specifying the name of the key column in the on option.

In [28]:
pd.merge(frame1,frame2,on='id')

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [29]:
pd.merge(frame1,frame2,on='brand')

      id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

As expected, the results vary considerably depending on the criteria of merging.

Often, however, the opposite problem arises, that is, to have two DataFrames in which the key columns do not have the same name. To remedy this situation, you have to use the left_on and right_on options that
specify the key column for the first and for the second DataFrame. Now you can see an example.

In [30]:
frame2.columns = ['brand','sid']
frame2

    brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [31]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')

Empty DataFrame
Columns: [id, color, brand_x, brand_y, sid]
Index: []

By default, the merge( ) function performs an inner join; the keys in the result are the result of an intersection.

Other possible options are the left join, the right join, and the outer join. The outer join produces the union of all keys, combining the effect of a left join with a right join. To select the type of join you have to use
the how option.

In [32]:
frame2.columns = ['id','brand']
pd.merge(frame1,frame2,on='id')

       id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [33]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [34]:
frame2

       id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [35]:
pd.merge(frame1,frame2,on='id',how='outer')

        id  color brand_x brand_y
0  ashtray  green     POD     NaN
1     ball  white     OMG     ABC
2      mug  black     POD     NaN
3      pen    red     ABC     POD
4   pencil    red     ABC     OMG
5   pencil    red     ABC     POD

In [36]:
pd.merge(frame1,frame2,on='id',how='left')

        id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [37]:
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

        id  color brand
0  ashtray  green   POD
1     ball    NaN   ABC
2     ball  white   OMG
3      mug  black   POD
4      pen    red   ABC
5      pen    NaN   POD
6   pencil    red   ABC
7   pencil    NaN   OMG
8   pencil    NaN   POD

## Explanation of `pd.merge` Operations

1.  **`pd.merge(frame1, frame2, on='id', how='outer')`**:
    *   This performs an **outer join** between `frame1` and `frame2` using the 'id' column as the key.
    *   An outer join includes all rows from both DataFrames. If an 'id' is present in one DataFrame but not the other, the corresponding columns from the missing DataFrame will be filled with `NaN` (Not a Number).
    *   For example, 'mug' and 'ashtray' from `frame1` have no matching 'id' in `frame2`, so their `brand_y` column is `NaN`. Conversely, if there were 'id's in `frame2` not in `frame1`, their `color` and `brand_x` would be `NaN`.

2.  **`pd.merge(frame1, frame2, on='id', how='left')`**:
    *   This performs a **left join** between `frame1` and `frame2` using the 'id' column.
    *   A left join includes all rows from the *left* DataFrame (`frame1` in this case) and only the matching rows from the *right* DataFrame (`frame2`).
    *   If an 'id' from `frame1` does not have a match in `frame2` (like 'mug' and 'ashtray'), the columns from `frame2` (`brand_y` here) will show `NaN` for those rows. All rows from `frame1` are preserved.

3.  **`pd.merge(frame1, frame2, on=['id', 'brand'], how='outer')`**:
    *   This is again an **outer join**, but this time the merge is performed on *two* keys: 'id' and 'brand'.
    *   For rows to be considered a match, both the 'id' *and* the 'brand' values must be identical in both DataFrames.
    *   If a combination of 'id' and 'brand' exists in `frame1` but not `frame2`, or vice-versa, that row is included with `NaN`s for the columns from the non-matching DataFrame. This creates a more granular merge criterion, often resulting in more `NaN`s if the two DataFrames don't have many exact matches across both specified columns.

#Merging on Index

In some cases, instead of considering the columns of a DataFrame as keys, the indexes could be used as keys on which to make the criteria for merging. Then in order to decide which indexes to consider, set the
left_index or right_index options to True to activate them, with the ability to activate them both.

In [38]:
frame1

        id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [39]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],'brand': ['OMG','POD','ABC','POD']})
frame2

       id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [40]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

     id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

But the DataFrame objects have a join() function which is much more convenient when you want to do the merging by indexes. It can also be used to combine many DataFrame objects having the same or the same indexes but with columns not overlapping.

In fact, if you launch

In [41]:
frame1.join(frame2)

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

You will get an error code because some columns of the frame1 have the same name of frame2. Then rename the columns of frame2 before launching the join( ) function.

In [42]:
frame2.columns = ['brand2','id2']
frame1.join(frame2)

        id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

Here you've performed a merging but based on the values of the indexes instead of the columns. This time there is also the index 4 that was present only in frame1, but the values corresponding to the columns of
frame2 report NaN as value.

## Common Use Cases for `pd.merge()`

`pd.merge()` is an incredibly powerful function for combining data from different DataFrames. Here are a few common scenarios where it proves invaluable:

1.  **Combining Customer Information with Order Details**: Enriching order records with customer demographics.
2.  **Joining Product Listings with Category Information**: Adding descriptive category names to product data.
3.  **Merging Sales Data with Regional Information**: Analyzing sales performance across different geographical regions.

### Use Case 1: Combining Customer Information with Order Details

Imagine you have one DataFrame with customer details (like `customer_id`, `name`, `city`) and another DataFrame with order details (`order_id`, `customer_id`, `product`, `amount`). You want to see which customer placed which order.

In [43]:
import pandas as pd

# Create a DataFrame for customer information
customers_df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston']
})

# Create a DataFrame for order details
orders_df = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105],
    'customer_id': [1, 2, 1, 3, 5], # Customer ID 5 doesn't exist in customers_df
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'amount': [1200, 25, 75, 300, 50]
})

print("Customers DataFrame:")
display(customers_df)

print("\nOrders DataFrame:")
display(orders_df)

# Merge customer and order data using a left join
# We use a left join to keep all customer information and add matching order details.
# Orders without a matching customer will result in NaN customer info (if an outer join was used).
# In this case, we want to see all customer data, and their corresponding orders.
merged_customer_orders = pd.merge(customers_df, orders_df, on='customer_id', how='left')

print("\nMerged Customer and Order Data (Left Join):")
display(merged_customer_orders)

# If we wanted to see only orders for existing customers, we would use an inner join
merged_customer_orders_inner = pd.merge(customers_df, orders_df, on='customer_id', how='inner')
print("\nMerged Customer and Order Data (Inner Join):")
display(merged_customer_orders_inner)

Customers DataFrame:

   customer_id     name         city
0            1    Alice     New York
1            2      Bob  Los Angeles
2            3  Charlie      Chicago
3            4    David      Houston

Orders DataFrame:

   order_id  customer_id   product  amount
0       101            1    Laptop    1200
1       102            2     Mouse      25
2       103            1  Keyboard      75
3       104            3   Monitor     300
4       105            5    Webcam      50

Merged Customer and Order Data (Left Join):

   customer_id     name         city  order_id   product  amount
0            1    Alice     New York     101.0    Laptop  1200.0
1            1    Alice     New York     103.0  Keyboard    75.0
2            2      Bob  Los Angeles     102.0     Mouse    25.0
3            3  Charlie      Chicago     104.0   Monitor   300.0
4            4    David      Houston       NaN       NaN     NaN

Merged Customer and Order Data (Inner Join):

   customer_id     name         city  order_id   product  amount
0            1    Alice     New York       101    Laptop    1200
1            1    Alice     New York       103  Keyboard      75
2            2      Bob  Los Angeles       102     Mouse      25
3            3  Charlie      Chicago       104   Monitor     300

### Use Case 2: Joining Product Listings with Category Information

Suppose you have a DataFrame of products (`product_id`, `product_name`, `category_id`) and another DataFrame with category details (`category_id`, `category_name`, `description`). You want to add the `category_name` to your product listings.

In [44]:
import pandas as pd

# Create a DataFrame for product listings
products_df = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003', 'P004'],
    'product_name': ['Smartphone', 'Tablet', 'Smartwatch', 'Headphones'],
    'category_id': [10, 20, 10, 30] # Category ID 30 doesn't exist in categories_df
})

# Create a DataFrame for category details
categories_df = pd.DataFrame({
    'category_id': [10, 20, 40],
    'category_name': ['Electronics', 'Computing', 'Accessories'],
    'description': ['Devices and gadgets', 'Computers and peripherals', 'Various accessories']
})

print("Products DataFrame:")
display(products_df)

print("\nCategories DataFrame:")
display(categories_df)

# Merge product and category data using a left join
# We use a left join to keep all products and add their category names.
merged_products_categories = pd.merge(products_df, categories_df, on='category_id', how='left')

print("\nMerged Products with Category Information (Left Join):")
display(merged_products_categories)

merged_products_categories2 = pd.merge(products_df, categories_df, on='category_id', how='inner')
print("\nMerged Products with Category Information (Inner Join):")
display(merged_products_categories2)

merged_products_categories3 = pd.merge(products_df, categories_df, on='category_id', how='outer')
print("\nMerged Products with Category Information (Outer Join):")
display(merged_products_categories3)

Products DataFrame:

  product_id product_name  category_id
0       P001   Smartphone           10
1       P002       Tablet           20
2       P003   Smartwatch           10
3       P004   Headphones           30

Categories DataFrame:

   category_id category_name                description
0           10   Electronics        Devices and gadgets
1           20     Computing  Computers and peripherals
2           40   Accessories        Various accessories

Merged Products with Category Information (Left Join):

,product_id,product_name,category_id,category_name,description
0,P001,Smartphone,10,Electronics,Devices and gadgets
1,P002,Tablet,20,Computing,Computers and peripherals
2,P003,Smartwatch,10,Electronics,Devices and gadgets
3,P004,Headphones,30,NaN,NaN

Merged Products with Category Information (Inner Join):

,product_id,product_name,category_id,category_name,description
0,P001,Smartphone,10,Electronics,Devices and gadgets
1,P002,Tablet,20,Computing,Computers and peripherals
2,P003,Smartwatch,10,Electronics,Devices and gadgets

Merged Products with Category Information (Outer Join):

,product_id,product_name,category_id,category_name,description
0,P001,Smartphone,10,Electronics,Devices and gadgets
1,P003,Smartwatch,10,Electronics,Devices and gadgets
2,P002,Tablet,20,Computing,Computers and peripherals
3,P004,Headphones,30,NaN,NaN
4,NaN,NaN,40,Accessories,Various accessories

### Use Case 3: Merging Sales Data with Regional Information

Consider having sales records (`sale_id`, `store_id`, `revenue`) and a separate DataFrame mapping `store_id` to `region_name`. You'd want to combine these to analyze sales by region.

In [45]:
import pandas as pd

# Create a DataFrame for sales data
sales_df = pd.DataFrame({
    'sale_id': [501, 502, 503, 504, 505],
    'store_id': ['S1', 'S2', 'S1', 'S3', 'S4'], # Store ID S4 doesn't exist in regions_df
    'revenue': [1500, 2300, 1800, 900, 700]
})

# Create a DataFrame for store regions
regions_df = pd.DataFrame({
    'store_id': ['S1', 'S2', 'S3', 'S5'], # Store ID S5 doesn't have sales data
    'region_name': ['North', 'South', 'West', 'East']
})

print("Sales DataFrame:")
display(sales_df)

print("\nRegions DataFrame:")
display(regions_df)

# Merge sales data with regional information using an inner join
# An inner join is appropriate here if we only want to analyze sales from stores that have region information.
merged_sales_regions = pd.merge(sales_df, regions_df, on='store_id', how='inner')

print("\nMerged Sales Data with Regional Information (Inner Join):")
display(merged_sales_regions)

# If we wanted to keep all sales records and see which ones don't have region info, we'd use a left join
merged_sales_regions_left = pd.merge(sales_df, regions_df, on='store_id', how='left')
print("\nMerged Sales Data with Regional Information (Left Join):")
display(merged_sales_regions_left)

Sales DataFrame:

   sale_id store_id  revenue
0      501       S1     1500
1      502       S2     2300
2      503       S1     1800
3      504       S3      900
4      505       S4      700

Regions DataFrame:

  store_id region_name
0       S1       North
1       S2       South
2       S3        West
3       S5        East

Merged Sales Data with Regional Information (Inner Join):

   sale_id store_id  revenue region_name
0      501       S1     1500       North
1      502       S2     2300       South
2      503       S1     1800       North
3      504       S3      900        West

Merged Sales Data with Regional Information (Left Join):

   sale_id store_id  revenue region_name
0      501       S1     1500       North
1      502       S2     2300       South
2      503       S1     1800       North
3      504       S3      900        West
4      505       S4      700         NaN

#Concatenating

Another type of data combination is referred to as concatenation. NumPy provides a concatenate()function to do this kind of operation with arrays.

In [46]:
array1=np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [49]:
np.concatenate([array1,array2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [48]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [50]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

As regards the pandas library and its data structures like Series and DataFrame, the fact of having labeled axes allows you to further generalize the concatenation of arrays. The concat() function is provided
by pandas for this kind of operation.

In [53]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

1    0.866927
2    0.256966
3    0.872093
4    0.014489
dtype: float64

In [52]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.427941
6    0.121003
7    0.079977
8    0.677669
dtype: float64

In [54]:
pd.concat([ser1,ser2])

1    0.866927
2    0.256966
3    0.872093
4    0.014489
5    0.427941
6    0.121003
7    0.079977
8    0.677669
dtype: float64

By default, the concat() function works on axis = 0, having as returned object a Series. If you set the axis = 1, then the result will be a DataFrame.

In [55]:
pd.concat([ser1,ser2],axis=1)

          0         1
1  0.866927       NaN
2  0.256966       NaN
3  0.872093       NaN
4  0.014489       NaN
5       NaN  0.427941
6       NaN  0.121003
7       NaN  0.079977
8       NaN  0.677669

From the result you can see that there is no overlap of data, therefore what you have just done is an outer join. This can be changed by setting the join option to ‘inner’.

In [56]:
pd.concat([ser1,ser2],axis=0,join='inner')

1    0.866927
2    0.256966
3    0.872093
4    0.014489
5    0.427941
6    0.121003
7    0.079977
8    0.677669
dtype: float64

A problem in this kind of operation is that the concatenated parts are not identifiable in the result. For example, you want to create a hierarchical index on the axis of concatenation. To do this you have to use the keys option.

In [57]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.866927
   2    0.256966
   3    0.872093
   4    0.014489
2  5    0.427941
   6    0.121003
   7    0.079977
   8    0.677669
dtype: float64

In the case of combinations between Series along the axis = 1 the keys become the column headers of the DataFrame.

In [58]:
pd.concat([ser1,ser2], axis=1, keys=[1,2])

          1         2
1  0.866927       NaN
2  0.256966       NaN
3  0.872093       NaN
4  0.014489       NaN
5       NaN  0.427941
6       NaN  0.121003
7       NaN  0.079977
8       NaN  0.677669

So far you have seen the concatenation applied to the Series, but the same logic can be applied to the DataFrame.

In [59]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[1,2,3],columns=['A','B','C'])
frame1

          A         B         C
1  0.446183  0.220049  0.140448
2  0.389700  0.521775  0.378710
3  0.075221  0.606674  0.578523

In [60]:
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), index=[4,5,6], columns=['A','B','C'])
frame2

          A         B         C
4  0.104069  0.236042  0.886030
5  0.091457  0.448557  0.804499
6  0.021324  0.200035  0.803294

In [62]:
pd.concat([frame1, frame2])

          A         B         C
1  0.446183  0.220049  0.140448
2  0.389700  0.521775  0.378710
3  0.075221  0.606674  0.578523
4  0.104069  0.236042  0.886030
5  0.091457  0.448557  0.804499
6  0.021324  0.200035  0.803294

In [61]:
pd.concat([frame1, frame2], axis=1)

          A         B         C         A         B         C
1  0.446183  0.220049  0.140448       NaN       NaN       NaN
2  0.389700  0.521775  0.378710       NaN       NaN       NaN
3  0.075221  0.606674  0.578523       NaN       NaN       NaN
4       NaN       NaN       NaN  0.104069  0.236042  0.886030
5       NaN       NaN       NaN  0.091457  0.448557  0.804499
6       NaN       NaN       NaN  0.021324  0.200035  0.803294

#Combining

There is another situation in which there is combination of data that cannot be obtained either with merging or with concatenation. Take the case in which you want the two datasets to have indexes that overlap in their entirety or at least partially.

One applicable function to Series is combine_first(), which performs this kind of operation along with an data alignment.

In [63]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
ser1

1    0.132179
2    0.145009
3    0.713679
4    0.893221
5    0.030676
dtype: float64

In [64]:
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
ser2

2    0.374481
4    0.858716
5    0.716321
6    0.356830
dtype: float64

In [65]:
ser1.combine_first(ser2)

1    0.132179
2    0.145009
3    0.713679
4    0.893221
5    0.030676
6    0.356830
dtype: float64

In [66]:
ser2.combine_first(ser1)

1    0.132179
2    0.374481
3    0.713679
4    0.858716
5    0.716321
6    0.356830
dtype: float64

Instead, if you want a partial overlap, you can specify only the portion of the Series you want to overlap.

In [67]:
ser1[:3].combine_first(ser2[:3])
# This operation combines the first three elements of `ser1` (by label) with the first three elements of `ser2` (by position).
# `combine_first` prioritizes non-NaN values from the first Series (`ser1[:3]`).
# For common indices (like '2'), `ser1`'s value is kept. For indices present only in `ser1[:3]` (like '1', '3'), its values are kept.
# For indices present only in `ser2[:3]` (like '4', '5'), their values are taken from `ser2`.
# Original ser1: 1    0.682345, 2    0.860347, 3    0.536425, 4    0.474636, 5    0.809059
# Original ser2: 2    0.252664, 4    0.756949, 5    0.862642, 6    0.388343
# ser1[:3] has indices 1, 2, 3.
# ser2[:3] has indices 2, 4, 5 (from original ser2).
# Output will have: Index 1 from ser1; Index 2 from ser1 (as ser1's value is not NaN); Index 3 from ser1; Index 4 from ser2; Index 5 from ser2.

1    0.132179
2    0.145009
3    0.713679
4    0.858716
5    0.716321
dtype: float64

#Pivoting

In addition to assembling the data in order to unify the values collected from different sources, another fairly common operation is pivoting. In fact, arrangement of the values by row or by column is not always
suited to your goals. Sometimes you would like to rearrange the data carrying column values on rows or vice versa.

#Pivoting with Hierarchical Indexing

You have already seen that DataFrame can support hierarchical indexing. This feature can be exploited to rearrange the data in a DataFrame. In the context of pivoting you have two basic operations:

• stacking: rotates or pivots the data structure converting columns to rows

• unstacking: converts rows into columns

In [68]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3), index=['white','black','red'], columns=['ball','pen','pencil'])
frame1

       ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [69]:
#Using the stack() function on the DataFrame, you will get the pivoting of the columns in rows, thus producing a Series:
ser5=frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int64

In [70]:
#From this hierarchically indexed series, you can reassemble the DataFrame into a pivoted table by use of the unstack() function
ser5.unstack()

       ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [71]:
#You can also do the unstack on a different level, specifying the number of levels or its name as the argument of the function.
ser5.unstack(0)

        white  black  red
ball        0      3    6
pen         1      4    7
pencil      2      5    8

In [72]:
ser5.unstack(1)

       ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

#Pivoting from “Long” to “Wide” Format

In [73]:
longframe = pd.DataFrame({ 'color':['white','white','white', 'red','red','red','black','black','black'], 'item':['ball','pen','mug', 'ball','pen','mug','ball','pen','mug'],
... 'value': np.random.rand(9)})
longframe

   color  item     value
0  white  ball  0.148577
1  white   pen  0.199720
2  white   mug  0.457090
3    red  ball  0.803135
4    red   pen  0.511457
5    red   mug  0.048883
6  black  ball  0.522048
7  black   pen  0.547383
8  black   mug  0.399550

In [74]:
wideframe = longframe.pivot(index='color', columns='item', values='value')
wideframe

item       ball       mug       pen
color
black  0.522048  0.399550  0.547383
red    0.803135  0.048883  0.511457
white  0.148577  0.457090  0.199720

#Removing

The last stage of data preparation is the removal of columns and rows. You

In [75]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3), index=['white','black','red'], columns=['ball','pen','pencil'])
frame1

       ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [76]:
#In order to remove a column, you have to simply use the del command applied to the DataFrame with the column name specified.
del frame1['ball']
frame1

       pen  pencil
white    1       2
black    4       5
red      7       8

In [77]:
#Instead, to remove an unwanted row, you have to use the drop() function with the label of the corresponding index as argument.
frame1.drop('white')

       pen  pencil
black    4       5
red      7       8